export enum ErrorCodes {
  // Erros de validação (400-499)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_ORDER_STATUS = 'INVALID_ORDER_STATUS',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',

  // Erros de servidor (500+)
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
